name: run-tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        laravel: [^6.0, ^7.0, ^8.0]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: ^6.0
            testbench: ^4.9.1
          - laravel: ^7.0
            testbench: ^5.9.1
          - laravel: ^8.0
            testbench: ^6.6.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Setup Memcached
        uses: niden/actions-memcached@v7

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install fzaninotto/faker
        if: ${{ matrix.php == '^7.4' }}
        run: |
          composer require "fzaninotto/faker:^1.9.1" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install fakerphp/faker
        if: ${{ matrix.php == '^8.0' }}
        run: |
          composer require "fakerphp/faker" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install laravel/legacy-factories
        if: ${{ matrix.laravel == '^8.0' }}
        run: |
          composer require "laravel/legacy-factories:^1.1" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tmp/clover.xml
